In [2]:
from statsbombpy import sb
import pandas as pd

In [4]:
competitions = sb.competitions()

c:\Users\emirc\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [5]:
competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [6]:
competitions.shape

(75, 12)

In [7]:
competitions.columns.tolist()

['competition_id',
 'season_id',
 'country_name',
 'competition_name',
 'competition_gender',
 'competition_youth',
 'competition_international',
 'season_name',
 'match_updated',
 'match_updated_360',
 'match_available_360',
 'match_available']

In [8]:
competitions[["competition_id", "season_id", "country_name", "competition_name", "season_name"]].drop_duplicates().head(30)

,competition_id,season_id,country_name,competition_name,season_name
0,9,281,Germany,1. Bundesliga,2023/2024
1,9,27,Germany,1. Bundesliga,2015/2016
2,1267,107,Africa,African Cup of Nations,2023
3,16,4,Europe,Champions League,2018/2019
4,16,1,Europe,Champions League,2017/2018
5,16,2,Europe,Champions League,2016/2017
6,16,27,Europe,Champions League,2015/2016
7,16,26,Europe,Champions League,2014/2015
8,16,25,Europe,Champions League,2013/2014
9,16,24,Europe,Champions League,2012/2013
10,16,23,Europe,Champions League,2011/2012
11,16,22,Europe,Champions League,2010/2011
12,16,21,Europe,Champions League,2009/2010
13,16,41,Europe,Champions League,2008/2009
14,16,39,Europe,Champions League,2006/2007
15,16,37,Europe,Champions League,2004/2005
16,16,44,Europe,Champions League,2003/2004
17,16,76,Europe,Champions League,1999/2000
18,16,277,Europe,Champions League,1972/1973
19,16,71,Europe,Champions League,1971/1972
20,16,276,Europe,Champions League,1970/1971
21,223,282,South America,Copa America,2024
22,87,84,Spain,Copa del Rey,1983/1984
23,87,268,Spain,Copa del Rey,1982/1983
24,87,279,Spain,Copa del Rey,1977/1978
25,37,90,England,FA Women's Super League,2020/2021
26,37,42,England,FA Women's Super League,2019/2020
27,37,4,England,FA Women's Super League,2018/2019
28,1470,274,International,FIFA U20 World Cup,1979
29,43,106,International,FIFA World Cup,2022

In [9]:
world_cup = competitions[
    competitions["competition_name"] == "FIFA World Cup"
][["competition_id", "season_id", "country_name", "competition_name", "season_name"]].drop_duplicates()

world_cup

    competition_id  season_id   country_name competition_name season_name
29              43        106  International   FIFA World Cup        2022
30              43          3  International   FIFA World Cup        2018
31              43         55  International   FIFA World Cup        1990
32              43         54  International   FIFA World Cup        1986
33              43         51  International   FIFA World Cup        1974
34              43        272  International   FIFA World Cup        1970
35              43        270  International   FIFA World Cup        1962
36              43        269  International   FIFA World Cup        1958

In [10]:
competition_id = 43
season_id = 106

In [11]:
matches = sb.matches(competition_id=competition_id, season_id=season_id)
matches.head()

c:\Users\emirc\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3857256,2022-12-02,21:00:00.000,International - FIFA World Cup,2022,Serbia,Switzerland,2,3,available,...,2023-04-26T23:49:58.956186,3,Group Stage,Stadium 974,Fernando Andrés Rapallini,Dragan Stojković,Murat Yakin,1.1.0,2,2
1,3869151,2022-12-03,21:00:00.000,International - FIFA World Cup,2022,Argentina,Australia,2,1,available,...,2023-07-30T07:48:51.865595,4,Round of 16,Ahmad bin Ali Stadium,Szymon Marciniak,Lionel Sebastián Scaloni,Graham James Arnold,1.1.0,2,2
2,3857257,2022-11-30,17:00:00.000,International - FIFA World Cup,2022,Australia,Denmark,1,0,available,...,2023-06-20T11:04:37.638969,3,Group Stage,Al Janoub Stadium,Mustapha Ghorbal,Graham James Arnold,Kasper Hjulmand,1.1.0,2,2
3,3857258,2022-11-24,21:00:00.000,International - FIFA World Cup,2022,Brazil,Serbia,2,0,available,...,2023-07-11T14:56:31.096588,1,Group Stage,Lusail Stadium,Alireza Faghani,Telê Santana da Silva,Dragan Stojković,1.1.0,2,2
4,3857288,2022-11-26,12:00:00.000,International - FIFA World Cup,2022,Tunisia,Australia,0,1,available,...,2023-04-27T00:30:07.835815,2,Group Stage,Al Janoub Stadium,Daniel Siebert,Jalel Kadri,Graham James Arnold,1.1.0,2,2

In [12]:
matches.shape

(64, 22)

In [13]:
matches.columns.tolist()

['match_id',
 'match_date',
 'kick_off',
 'competition',
 'season',
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'match_status',
 'match_status_360',
 'last_updated',
 'last_updated_360',
 'match_week',
 'competition_stage',
 'stadium',
 'referee',
 'home_managers',
 'away_managers',
 'data_version',
 'shot_fidelity_version',
 'xy_fidelity_version']

In [14]:
matches[["match_id", "home_team", "away_team", "match_date"]].head(20)

    match_id     home_team    away_team  match_date
0    3857256        Serbia  Switzerland  2022-12-02
1    3869151     Argentina    Australia  2022-12-03
2    3857257     Australia      Denmark  2022-11-30
3    3857258        Brazil       Serbia  2022-11-24
4    3857288       Tunisia    Australia  2022-11-26
5    3857267       Ecuador      Senegal  2022-11-29
6    3869321   Netherlands    Argentina  2022-12-09
7    3857287       Uruguay  South Korea  2022-11-24
8    3869486       Morocco     Portugal  2022-12-10
9    3869685     Argentina       France  2022-12-18
10   3857260  Saudi Arabia       Mexico  2022-11-30
11   3857264        Poland    Argentina  2022-11-30
12   3857266        France      Denmark  2022-11-26
13   3857289     Argentina       Mexico  2022-11-26
14   3857269        Brazil  Switzerland  2022-11-28
15   3857294   Netherlands        Qatar  2022-11-29
16   3869254      Portugal  Switzerland  2022-12-06
17   3869118       England      Senegal  2022-12-04
18   3869684       Croatia      Morocco  2022-12-17
19   3869519     Argentina      Croatia  2022-12-13

In [15]:
match_id = matches.iloc[0]["match_id"]

In [16]:
events = sb.events(match_id=match_id)
events.head()

c:\Users\emirc\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 3412, 'lineup': [{'player': {'id...",Serbia,786,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4231, 'lineup': [{'player': {'id...",Switzerland,773,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Switzerland,773,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Serbia,786,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Serbia,786,00:00:00.000,Half Start,NaN

In [17]:
events.shape

(3211, 91)

In [18]:
events.columns.tolist()

['bad_behaviour_card',
 'ball_receipt_outcome',
 'ball_recovery_recovery_failure',
 'block_deflection',
 'block_offensive',
 'carry_end_location',
 'clearance_aerial_won',
 'clearance_body_part',
 'clearance_head',
 'clearance_left_foot',
 'clearance_right_foot',
 'counterpress',
 'dribble_nutmeg',
 'dribble_outcome',
 'duel_outcome',
 'duel_type',
 'duration',
 'foul_committed_advantage',
 'foul_committed_card',
 'foul_committed_type',
 'foul_won_advantage',
 'foul_won_defensive',
 'goalkeeper_body_part',
 'goalkeeper_end_location',
 'goalkeeper_outcome',
 'goalkeeper_position',
 'goalkeeper_technique',
 'goalkeeper_type',
 'id',
 'index',
 'injury_stoppage_in_chain',
 'interception_outcome',
 'location',
 'match_id',
 'minute',
 'off_camera',
 'out',
 'pass_aerial_won',
 'pass_angle',
 'pass_assisted_shot_id',
 'pass_body_part',
 'pass_cross',
 'pass_cut_back',
 'pass_deflected',
 'pass_end_location',
 'pass_goal_assist',
 'pass_height',
 'pass_length',
 'pass_miscommunication',
 'pass_outcome',
 'pass_outswinging',
 'pass_recipient',
 'pass_recipient_id',
 'pass_shot_assist',
 'pass_switch',
 'pass_technique',
 'pass_through_ball',
 'pass_type',
 'period',
 'play_pattern',
 'player',
 'player_id',
 'position',
 'possession',
 'possession_team',
 'possession_team_id',
 'related_events',
 'second',
 'shot_aerial_won',
 'shot_body_part',
 'shot_deflected',
 'shot_end_location',
 'shot_first_time',
 'shot_freeze_frame',
 'shot_key_pass_id',
 'shot_one_on_one',
 'shot_open_goal',
 'shot_outcome',
 'shot_statsbomb_xg',
 'shot_technique',
 'shot_type',
 'substitution_outcome',
 'substitution_outcome_id',
 'substitution_replacement',
 'substitution_replacement_id',
 'tactics',
 'team',
 'team_id',
 'timestamp',
 'type',
 'under_pressure']

In [19]:
events["type"].value_counts()

type
Pass                 966
Ball Receipt*        907
Carry                667
Pressure             177
Ball Recovery         92
Duel                  68
Block                 40
Clearance             36
Foul Committed        35
Foul Won              34
Goal Keeper           30
Shot                  26
Miscontrol            25
Interception          23
Dispossessed          23
Dribble               12
Injury Stoppage       10
Substitution           9
Dribbled Past          6
Referee Ball-Drop      4
Half Start             4
Half End               4
Bad Behaviour          4
Tactical Shift         2
Starting XI            2
Error                  2
Player Off             1
Player On              1
Shield                 1
Name: count, dtype: int64

In [20]:
events["team"].value_counts()

team
Serbia         1723
Switzerland    1488
Name: count, dtype: int64

In [21]:
events["player"].value_counts().head(20)

player
Strahinja Pavlović              250
Saša Lukić                      192
Nikola Milenković               182
Granit Xhaka                    174
Silvan Widmer                   168
Filip Kostić                    155
Dušan Tadić                     147
Manuel Obafemi Akanji           144
Ricardo Iván Rodríguez Araya    132
Fabian Lukas Schär              132
Breel-Donald Embolo             121
Vanja Milinković Savić          120
Aleksandar Mitrović             117
Remo Freuler                    111
Andrija Živković                110
Xherdan Shaqiri                 105
Djibril Sow                      96
Ruben Vargas                     94
Milos Veljkovic                  92
Sergej Milinković-Savić          90
Name: count, dtype: int64

In [22]:
events[["type", "team", "player", "minute", "location"]].head(20)

           type         team                 player  minute       location
0   Starting XI       Serbia                    NaN       0            NaN
1   Starting XI  Switzerland                    NaN       0            NaN
2    Half Start  Switzerland                    NaN       0            NaN
3    Half Start       Serbia                    NaN       0            NaN
4    Half Start       Serbia                    NaN      45            NaN
5    Half Start  Switzerland                    NaN      45            NaN
6          Pass  Switzerland    Breel-Donald Embolo       0   [61.0, 40.1]
7          Pass  Switzerland           Remo Freuler       0   [39.7, 45.5]
8          Pass  Switzerland          Silvan Widmer       0   [42.3, 72.2]
9          Pass  Switzerland     Fabian Lukas Schär       0   [23.1, 62.4]
10         Pass  Switzerland            Djibril Sow       0  [105.6, 74.4]
11         Pass  Switzerland        Xherdan Shaqiri       0  [105.6, 47.5]
12         Pass  Switzerland  Manuel Obafemi Akanji       0   [77.7, 35.9]
13         Pass       Serbia       Andrija Živković       0   [20.0, 80.0]
14         Pass       Serbia             Saša Lukić       0   [22.8, 71.9]
15         Pass  Switzerland            Djibril Sow       0  [113.6, 12.4]
16         Pass  Switzerland     Fabian Lukas Schär       0   [31.9, 50.4]
17         Pass  Switzerland           Gregor Kobel       1    [7.6, 40.9]
18         Pass  Switzerland     Fabian Lukas Schär       1   [34.9, 74.6]
19         Pass  Switzerland            Djibril Sow       1   [49.2, 53.6]

In [23]:
len(events)
events["type"].value_counts()
events["team"].value_counts()
events.groupby(["minute", "team"]).size().reset_index(name="count").head()

   minute         team  count
0       0       Serbia     16
1       0  Switzerland     32
2       1       Serbia     24
3       1  Switzerland     18
4       2       Serbia     28

In [25]:
events["player"].value_counts()

player
Strahinja Pavlović              250
Saša Lukić                      192
Nikola Milenković               182
Granit Xhaka                    174
Silvan Widmer                   168
Filip Kostić                    155
Dušan Tadić                     147
Manuel Obafemi Akanji           144
Ricardo Iván Rodríguez Araya    132
Fabian Lukas Schär              132
Breel-Donald Embolo             121
Vanja Milinković Savić          120
Aleksandar Mitrović             117
Remo Freuler                    111
Andrija Živković                110
Xherdan Shaqiri                 105
Djibril Sow                      96
Ruben Vargas                     94
Milos Veljkovic                  92
Sergej Milinković-Savić          90
Gregor Kobel                     68
Nemanja Gudelj                   58
Nemanja Maksimović               55
Dušan Vlahović                   52
Edimilson Fernandes              51
Luka Jović                       45
Christian Fassnacht              38
Denis Lemi Zakaria Lako Lado     35
Nemanja Radonjić                 31
Filip Đuričić                    18
Noah Okafor                      11
Predrag Rajković                  1
Name: count, dtype: int64

In [27]:
shots = events[events["type"] == "Shot"].copy()
shots["player"].value_counts()

player
Granit Xhaka             3
Breel-Donald Embolo      3
Dušan Vlahović           3
Aleksandar Mitrović      3
Remo Freuler             2
Xherdan Shaqiri          2
Luka Jović               2
Nikola Milenković        1
Andrija Živković         1
Ruben Vargas             1
Fabian Lukas Schär       1
Dušan Tadić              1
Manuel Obafemi Akanji    1
Christian Fassnacht      1
Nemanja Radonjić         1
Name: count, dtype: int64

In [29]:
shots = events[events["type"] == "Shot"].copy()
shots["shot_outcome"].value_counts()
shots[["team", "player", "minute", "location", "shot_outcome"]]

             team                 player  minute       location shot_outcome
2674  Switzerland           Granit Xhaka       0   [96.0, 38.8]      Blocked
2675  Switzerland    Breel-Donald Embolo       0  [113.1, 40.7]        Saved
2676  Switzerland           Granit Xhaka       0  [103.8, 41.9]        Saved
2677       Serbia      Nikola Milenković       4  [112.2, 36.8]        Off T
2678       Serbia       Andrija Živković      10   [97.8, 51.5]         Post
2679       Serbia         Dušan Vlahović      10  [115.4, 38.6]        Saved
2680  Switzerland           Remo Freuler      13  [107.8, 35.9]      Blocked
2681  Switzerland        Xherdan Shaqiri      19  [107.5, 50.6]         Goal
2682  Switzerland           Granit Xhaka      21   [97.3, 33.7]        Saved
2683       Serbia         Dušan Vlahović      22  [109.6, 35.4]        Saved
2684       Serbia    Aleksandar Mitrović      25  [108.3, 38.6]         Goal
2685  Switzerland        Xherdan Shaqiri      29  [107.7, 49.2]        Off T
2686       Serbia         Dušan Vlahović      34  [106.2, 31.8]         Goal
2687  Switzerland           Ruben Vargas      37  [101.0, 47.3]      Blocked
2688  Switzerland    Breel-Donald Embolo      43  [114.4, 36.9]         Goal
2689       Serbia    Aleksandar Mitrović      47  [101.7, 33.7]      Wayward
2690  Switzerland           Remo Freuler      47  [107.2, 41.2]         Goal
2691  Switzerland     Fabian Lukas Schär      56  [110.7, 30.5]      Blocked
2692  Switzerland    Breel-Donald Embolo      56  [116.1, 39.3]        Off T
2693       Serbia            Dušan Tadić      60  [107.4, 31.7]        Off T
2694       Serbia    Aleksandar Mitrović      70  [106.2, 25.8]      Blocked
2695       Serbia             Luka Jović      72  [102.2, 43.2]      Blocked
2696  Switzerland  Manuel Obafemi Akanji      81   [99.4, 52.7]        Off T
2697  Switzerland    Christian Fassnacht      88  [105.3, 28.9]        Saved
2698       Serbia             Luka Jović      91  [105.0, 39.8]        Off T
2699       Serbia       Nemanja Radonjić      99  [105.7, 51.3]        Off T